### ISSUE TITLE
Subtype parameter in Teams plugin is incorrect - should be "object_subtype"

### ISSUE THREAD

**Issue by kandrews-alp** [industrialdev/wicket-wordpressplugin-php#4]
The subtype parameter is incorrect when passed in the register_meta functions here:
https://github.com/industrialdev/wicket-wordpressplugin-php/blob/master/wicket_woocommerce_membership_team.php#L28

The parameter should be "object_subtype" as mentioned here: 
https://developer.wordpress.org/reference/functions/register_meta/

This is causing the meta fields to be registered to all post types and in recent versions of WordPress, prevents changes on pages/posts from being saved in the admin.

![image001](https://github.com/user-attachments/assets/12cca097-9993-4931-8a7c-fb2a5b34335d)

**Comment by rferguson10** [comment]
patched
